### ISSUE TITLE
How to restart iceweasel if closed by user

### ISSUE THREAD

**Issue by ebeeker** [elalemanyo/raspberry-pi-kiosk-screen#10]
I've setup a pi-kiosk using iceweasel, and it works great ... except if the user closes the last tab on the browser there is no way to reload it/get it back -- you're just left with a black screen. You can restart the pi and get it back, but I'd rather have the user be able to do it.

Is there a way to link the browser restart to an F key? Or create a cron job that checks every minute to see if the browser is open, and if not restart it? There is the cron job to refresh to F5, but not restart from scratch.

Other than this, the setup has been perfect for me. Thanks in advance.

**Comment by elalemanyo** [comment]
Maybe you can add a script to crontab where you check if iceweasel is running and if not start it.
Maybe something like this:

```bash
#!/bin/bash
ICEWEASEL_RUNNING=$(pgrep -c iceweasel)

if [[ "$ICEWEASEL_RUNNING" -eq 0 ]]; then
    unclutter &
    matchbox-window-manager &
    iceweasel [URL] --display=:0 &
    sleep 15s;
    xte "key F11" -x:0
fi
```

Let me know if it works.
